[[actions]]
name = "Default"
path = "Sample Evil App{{EXT}}"
scope = "profile:me"

[[actions]]
name = "Sandbox opt-in"
path = "Sample Evil App{{EXT}}"
scope = "profile:me"
sandbox = true

[[actions]]
name = "Args"
path = "Sample Evil App{{EXT}}"
args = ["being", "john", "malkovich"]

[[prereqs]]
name = "vcredist-2010-x86"

